language: node_js
node_js:
  - 4
  - 5
  - 6

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

#before_script:
#  - npm install -g grunt-cli

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm install

script:
  - npm run lint
  - npm run test-cov

branches:
  only:
    - gh-pages
#after_success:
#    - npm run coveralls

#after_success:
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
